#----------------------------------------------
# INICIALIZAÇÃO DO CLUSTER
#----------------------------------------------

- name: Initialize the cluster using docker swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_host }}"
    listen_addr: "0.0.0.0"
  register: master_output

- name: get join command
  shell: 'docker swarm join-token worker | grep join'
  register: join_command_raw

- name: set join command
  set_fact:
    join_command: '{{ join_command_raw.stdout_lines[0] }}'