---
all:
  vars:
    ambiente: virtualbox
    ansible_user: vagrant
    ansible_ssh_private_key_file: keys/docker
    cluster_enabled: true

  hosts:
    master-01:
      ansible_host: 192.168.50.111
    node-01:
      ansible_host: 192.168.50.112
    node-02:
      ansible_host: 192.168.50.113
    node-03:
      ansible_host: 192.168.50.114


  children:
    master:
      hosts:
        master-01:
        
    worker:
      hosts:
        node-01:
        node-02:
        node-03: