machines = {
  "master-01" => {"memory" => "2048", "cpu" => "2", "ip" => "111", "image" => "bento/ubuntu-20.04"},
  "node-01"   => {"memory" => "2048", "cpu" => "2", "ip" => "112", "image" => "bento/ubuntu-20.04"},
  "node-02"   => {"memory" => "2048", "cpu" => "2", "ip" => "113", "image" => "bento/ubuntu-20.04"},
  "node-03"   => {"memory" => "2048", "cpu" => "2", "ip" => "114", "image" => "bento/ubuntu-20.04"}

}

Vagrant.configure("2") do |config|

    machines.each do |name, conf|
        config.vm.define "#{name}" do |machine|

            # Configurações iniciais das vms
            machine.vm.box = "#{conf["image"]}"
            machine.vm.hostname = "#{name}.lab.docker.io"
            machine.vm.network "private_network", ip: "192.168.50.#{conf["ip"]}"

            # Provisionamento do Docker
            machine.vm.provision :docker

            # Adicionando ssh keys
            machine.vm.provision "shell" do |s|
                ssh_pub_key = File.readlines("./keys/docker.pub").first.strip
                s.inline = <<-SHELL
                echo "Ambiente para laboratório: Desafio Docker Swarm - DIOs" > /tmp/vagrant.txt
            SHELL
            end

            # Recursos
            machine.vm.provider "virtualbox" do |vb|
                vb.name = "#{name}"
                vb.memory = conf["memory"]
                vb.cpus = conf["cpu"]
            end
        end
    end
end