---
#---------------------------------------------------
# CONFIGURAÇÃO DO WORKER
#---------------------------------------------------

- name: join cluster
  shell: "{{ hostvars['master-01'].join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt